name: Go

on:
    push:
        branches:
            - $default-branch
    pull_request:
        branches:
            - $default-branch
    workflow_dispatch: {}

jobs:
    update:
        script:
            - apt-get update

    deps:
        needs:
            - update
        script:
            - apt install tk xvfb -y --no-install-recommends

    build:
        needs:
            - deps
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
                uses: actions/setup-go@v4
                with:
                    go-version: '1.21'
            - name: Build
                run: go build -v ./...
            - name: Test
                run: xvfb-run go test -v ./...

